### ISSUE TITLE
语音在线合成无法读取后端错误

### ISSUE THREAD

**Issue by AureliusPatiens** [Baidu-AIP/java-sdk#1]
String contentType = res.getHeader().get("Content-type").get(0);
        if (contentType.contains("json")) {
            String data = res.getBodyStr();
            JSONObject json = new JSONObject(data);

            System.out.println(json.toString());

            response.setErrorCode(json.getInt("err_no"));
            response.setErrorMsg(json.getString("err_msg"));
            response.setSn(json.getString("sn"));
            response.setIdx(json.getInt("idx"));
            return response;
        }

当以上代码(处于AipSpeech 133-140之间)获取到如以下报错时:
{"err_msg":"backend error.","err_detail":"Internal error","tts_logid":1547034651,"err_subcode":20211,"err_no":503}
会因为无法获取"sn"同"idx"导致JSON解析异常
Exception in thread "main" org.json.JSONException: JSONObject["sn"] not found.
	at org.json.JSONObject.get(JSONObject.java:520)
	at org.json.JSONObject.getString(JSONObject.java:806)
	at com.baidu.aip.speech.AipSpeech.synthesis(AipSpeech.java:142)

**Comment by flyhighzy** [comment]
感谢提issue告知~
这个问题修复已经在计划中，预计11月中旬上线

**Comment by flyhighzy** [comment]
新版已上线，请至官网下载使用:)  http://ai.baidu.com/sdk#tts
