### ISSUE TITLE
在线语音合成，有时候出现错误，过一段时间就好了(大概5分钟)

### ISSUE THREAD

**Issue by yuanzhe08** [Baidu-AIP/java-sdk#10]
错误消息:{"error_msg":"No permission to access data","error_code":6},这种错误是经常性出现，

**Comment by xiaoshuaishuai319** [comment]
是不是应用错误了 或者重新创建一个语音应用 这个错误意思没权限访问 可以去论坛看我写的帖子 如何勾选

**Comment by flyhighzy** [comment]
同意楼上回答~
另外多次请求可以利用AipSpeech类，不需要每次请求都建立一个新的AipSpeech对象，可以减少出现鉴权问题的概率。

**Comment by PeterPanZH** [comment]
请提供更加详细信息，包括你的代码，方便我们确定问题，非常感谢
