### ISSUE TITLE
仓库下载的最新版本。和源码匹配不上

### ISSUE THREAD

**Issue by xiaoshuaishuai319** [Baidu-AIP/java-sdk#11]
最新版本4.1.0 。里面包含了txtcensor包。文本审核模块。但是在github的源代码中。是没有这个模块的。麻烦修复一下

**Comment by flyhighzy** [comment]
感谢指正~
txtcensor包中的接口属于未正式发布版本，百度云上也没有勾选权限的入口，不影响其它接口使用。maven仓库中4.1.1版本已去除。
