### ISSUE TITLE
百度下载的 SDK 4.1.1 中使用了log4j。可否去除log4j的依赖

### ISSUE THREAD

**Issue by csgajcr** [Baidu-AIP/java-sdk#13]
因我们需要将SDK应用于自己的项目中，而项目中没有使用log4j，如果要使用4.1.1的SDK就必须导入log4j，这样对我们的项目开发不太友好。

**Comment by flyhighzy** [comment]
暂时还需要打印日志方便排查用户问题~
如果自己不需要，可以下载源代码去掉相关依赖
