### ISSUE TITLE
建议AipImageClassify增加EasyDL接口调用方法

### ISSUE THREAD

**Issue by xiaoshuaishuai319** [Baidu-AIP/java-sdk#16]
/**
	 * EasyDL接口调用
	 * @param uri easydl平台生成的接口地址
	 * @param image  - 二进制图像数据
	 * @param options - 可选参数对象，key: value都为string类型
     * options - options列表:
	 * @return JSONObject
	 */
	public JSONObject easydlClassify(String uri,byte[] file, HashMap<String, String> options) {
		AipRequest request = new AipRequest();
		preOperation(request);
		String image = Base64Util.encode(file);
		request.addBody("image", image);
        if (options != null) {
            request.addBody(options);
        }
		request.setUri(uri);
		request.addHeader(Headers.CONTENT_ENCODING,
				HttpCharacterEncoding.ENCODE_UTF8);
		request.addHeader(Headers.CONTENT_TYPE, HttpContentType.JSON_DATA);
		request.setBodyFormat(EBodyFormat.RAW_JSON);
		postOperation(request);
		return requestServer(request);
	}
	/**
	 * EasyDL接口调用
	 * @param uri easydl平台生成的接口地址
	 * @param image  - 本地图片路径
 	 * @param options - 可选参数对象，key: value都为string类型
     * options - options列表:
	 * @return JSONObject
	 */
	public JSONObject easydlClassify(String uri,String image, HashMap<String, String> options) {
        try {
            byte[] data = Util.readFileByBytes(image);
            return easydlClassify(uri,data,options);
        } catch (IOException e) {
            e.printStackTrace();
            return AipError.IMAGE_READ_ERROR.toJsonResult();
        }
	}

**Comment by PeterPanZH** [comment]
感谢小帅~
EasyDL后续可能会拆一个新的类型出来，这个issue先开着吧~

**Comment by flyhighzy** [comment]
EasyDL的服务已添加至SDK，欢迎使用~
