### ISSUE TITLE
项目都有自己的日志实现，建议将log4j修改为slf4j

### ISSUE THREAD

**Issue by ydq** [Baidu-AIP/java-sdk#17]
如题，现在项目都有自己的日志实现了，这样强依赖log4j真的好么？

**Comment by flyhighzy** [comment]
感谢建议。加上日志的初衷是为了方便排查客户问题，但观察下来发现作用并不大，后续可能考虑去掉日志依赖.

**Comment by cn-src** [comment]
还是使用 slf4j 吧，至少需要 debug 日志。

**Comment by zhouyougit** [comment]
关键还强依赖了log4j，而且还是1.x版本的log4j，赶紧升级吧，不然都没法用

**Comment by flyhighzy** [comment]
下一版本将升级日志为slf4j, 预计1.25上线，欢迎使用反馈

**Comment by flyhighzy** [comment]
已更新，欢迎更新到4.10.2版本
