### ISSUE TITLE
建议百度自己抽象一个JSON接口，然后让用户去实现它

### ISSUE THREAD

**Issue by ydq** [Baidu-AIP/java-sdk#18]
目前用的是json库，建议百度自己抽象一个converter，抽象出具体要的接口方法（比如传入json字符串，返回api需要的对象，而不是现有的什么JSONObject），然后让开发者自己实现这个converter，比起强制指定一个json库要优雅的多。毕竟现在市面上流行的json库那么多，如jackson、fastjson、gson、jsonlib等等，如果用户自己的项目中已有json库的实现了，为什么还需要额外引入一个json库呢？

**Comment by flyhighzy** [comment]
感谢建议。我们会综合考虑改造成本和用户反馈来决定是否进行这样的改造，同时，sdk也是开源的，欢迎提pr~

**Comment by flyhighzy** [comment]
SDK同时需要考虑易用性，为刚上手的开发同学提供便利，暂时不会更新Json接口~
