### ISSUE TITLE
AipFace中search方法问题

### ISSUE THREAD

**Issue by xiaoshuaishuai319** [Baidu-AIP/java-sdk#20]
测试发现。接口请求会返回
`{"result":null,"log_id":201810171049,"error_msg":"param[image] is null","cached":0,"error_code":222001,"timestamp":1539744457}
`
SDK和文档都写的为JSON格式拼接。亲测是KV形式拼接。

**Comment by flyhighzy** [comment]
可能是后端服务临时问题，已确认SDK中调用方式无误
