### ISSUE TITLE
SpringMVC cannot map requests after importing Baidu Aip into Maven POM/在Maven配置里面添加百度SDK之后SpringMVC不能映射请求

### ISSUE THREAD

**Issue by No5972** [Baidu-AIP/java-sdk#22]
Encountered a problem about SpringMVC, Maven and Baidu Aip SDK conflicts.
After adding 

		<dependency>
			<groupId>com.baidu.aip</groupId>
			<artifactId>java-sdk</artifactId>
			<version>${baidu.aip.version}</version>
		</dependency>
this into Maven POM, SpringMVC cannot map requests. The console does not display mapping information. But once deleting this, SpringMVC can map requests again. By the way, another situation has been noticed: maunally creating a web project without using Maven and manually import AIP Java SDK won't cause SpringMVC not mapping. I would like to know how to solve the problem, thanks...
SpringMVC: 4.1.0 Baidu SDK: 4.1.1 Maven: 3.6.0 JDK: 1.7.0_79
EDITED: Used Baidu SDK 4.8.0 but the same issue still persists.
遇到关于SpringMVC、Maven和百度AIP SDK冲突的问题。
在Maven的POM里面加入这个依赖之后，SpringMVC就不能映射请求了，控制台也不显示映射的信息。但是如果删掉这个依赖就又可以映射请求了。另外注意到这个现象，手动创建web项目，不使用Maven，手动导包则不会出现SpringMVC不进行映射的问题。希望知道如何解决这个问题，谢谢。。。
SpringMVC: 4.1.0 Baidu SDK: 4.1.1 Maven: 3.6.0 JDK: 1.7.0_79
编辑：换成4.8.0的百度SDK问题同样存在。

[pom.zip](https://github.com/Baidu-AIP/java-sdk/files/2667498/pom.zip)

**Comment by flyhighzy** [comment]
麻烦贴一下比较详细的报错日志

**Comment by No5972** [comment]
Issue fixed automatically. Thanks for support...
Tried re-deploying project today, it has been automatically recovered.
EDITED: Console still doesn't display mapping information but the requests can be normally handled.
问题已自动恢复，感谢支持。。。
今天尝试重新部署项目，已经自动恢复正常。
编辑：控制台还是不显示映射信息，但是请求已经可以正常处理。
[detailederrlog.zip](https://github.com/Baidu-AIP/java-sdk/files/2676501/detailederrlog.zip)
