### ISSUE TITLE
语音合成,会报空指针问题

### ISSUE THREAD

**Issue by a532960944** [Baidu-AIP/java-sdk#6]
java.lang.NullPointerException
        at com.baidu.aip.speech.AipSpeech.synthesis(AipSpeech.java:132)

**Comment by xiaoshuaishuai319** [comment]
是的。 String contentType = res.getHeader().get("Content-type").get(0); Content-type t小写导致。实际返回的T是大写

**Comment by flyhighzy** [comment]
是的，后端服务器有升级，导致sdk读取出错。sdk问题已修复，做了兼容处理，请至官网下载最新3.4.1版本使用；github代码和maven仓库也已同步更新。
